#!/bin/sh
#
#  Andrew McNab, University of Manchester.
#  Copyright (c) 2013-9. All rights reserved.
#
#  Redistribution and use in source and binary forms, with or
#  without modification, are permitted provided that the following
#  conditions are met:
#
#    o Redistributions of source code must retain the above
#      copyright notice, this list of conditions and the following
#      disclaimer. 
#    o Redistributions in binary form must reproduce the above
#      copyright notice, this list of conditions and the following
#      disclaimer in the documentation and/or other materials
#      provided with the distribution. 
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND
#  CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
#  INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
#  DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS
#  BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
#  EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
#  TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
#  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
#  ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
#  OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
#  OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#  POSSIBILITY OF SUCH DAMAGE.
#
#  Contacts: Andrew.McNab@cern.ch
#

if [ "$1" = "" -o "$2" = "" ] ; then
  echo vmcondor-approve USERNAME EMAIL@ADDRESS
  exit 0
fi

if [ -s "/var/lib/vmcondor-ca/approved/$1" ] ; then
  echo "/var/lib/vmcondor-ca/approved/$1 already exists!"
  exit 1
fi

if [ ! -s "/var/lib/vmcondor-ca/incoming/$1" ] ; then
  echo "/var/lib/vmcondor-ca/incoming/$1 does not exist!"
  exit 1
fi

(

  echo "FQAN=/iris.ac.uk/Role=NULL/Capability=NULL"
  echo "EMAIL=$2"
  cat "/var/lib/vmcondor-ca/incoming/$1"

) > "/var/lib/vmcondor-ca/approved/$1"

newUID=1`echo "$1" | cut -c5-8`

useradd --home-dir /var/lib/condor --comment "VMCondor $1" --no-create-home --shell /sbin/nologin --uid $newUID  "$1"

(
  cd /var/lib/vmcondor-ca/approved

  echo '# DO NOT EDIT - CREATED BY vmcondor-approve'
  echo 'GSI "/C=UK/O=eScience/OU=Manchester/L=HEP/CN=iris-vm.blackett.manchester.ac.uk" condor'
  echo 'GSI "/C=UK/O=eScience/OU=Manchester/L=HEP/CN=andrew mcnab" condor'

  for username in `ls | grep '^user[0-9][0-9][0-9][0-9]$'`
  do
    echo 'GSI "/O=vmcondor.iris.ac.uk/CN='${username}'" '${username}
  done
) > /etc/condor/certificate_mapfile.tmp

mv -f /etc/condor/certificate_mapfile.tmp /etc/condor/certificate_mapfile

condor_reconfig -all

